// packages/fullstack/examples/vue-router/src/framework/entry.client.tsx
import { createHead } from "@unhead/vue/client";
import { createSSRApp } from "vue";
import { createRouter, createWebHistory } from "vue-router";
import Root from "../root.vue";
import { routes } from "../routes";

async function main() {
  const app = createSSRApp(Root);

  const router = createRouter({
    history: createWebHistory(),
    routes,
  });
  app.use(router);

  const head = createHead();
  app.use(head);

  await router.isReady();
  app.mount("#root");

  if (import.meta.hot) {
    // TODO
    import.meta.hot.on("fullstack:update", (e) => {
      console.log("[fullstack:update]", e);
      window.location.reload();
    });
  }
}

main();

// packages/fullstack/examples/cloudflare/src/entry.client.tsx
import "@vitejs/plugin-react-swc/preamble";
import { StrictMode, startTransition } from "react";
import { hydrateRoot } from "react-dom/client";
import { App } from "./App";

function main() {
  startTransition(() => {
    hydrateRoot(
      document.getElementById("root")!,
      <StrictMode>
        <App />
      </StrictMode>,
    );
  });

  if (import.meta.hot) {
    // TODO
    import.meta.hot.on("fullstack:update", (e) => {
      console.log("[fullstack:update]", e);
      window.location.reload();
    });
  }
}

main();
