// packages/fullstack/examples/island/src/entry.client.tsx
// @ts-ignore
import "virtual:react-hmr-preamble";
import "./styles/client.css";
import { createRoot } from "react-dom/client";
import { Counter } from "./components/counter";

function main() {
  const domRoot = document.getElementById("client-app")!;
  createRoot(domRoot).render(<App />);

  if (import.meta.hot) {
    // TODO
    import.meta.hot.on("fullstack:update", (e) => {
      console.log("[fullstack:update]", e);
      window.location.reload();
    });
  }
}

function App() {
  return (
    <div style={{ border: "2px solid orange", padding: "1rem" }}>
      <h4>Client-only island</h4>
      <Counter />
      <div className="test-client-style">test-client-style</div>
    </div>
  );
}

main();

// packages/fullstack/examples/vue-router/src/framework/entry.client.tsx
import { createHead } from "@unhead/vue/client";
import { createSSRApp } from "vue";
import { createRouter, createWebHistory } from "vue-router";
import Root from "../root.vue";
import { routes } from "../routes";

async function main() {
  const app = createSSRApp(Root);

  const router = createRouter({
    history: createWebHistory(),
    routes,
  });
  app.use(router);

  const head = createHead();
  app.use(head);

  await router.isReady();
  app.mount("#root");

  if (import.meta.hot) {
    // TODO
    import.meta.hot.on("fullstack:update", (e) => {
      console.log("[fullstack:update]", e);
      window.location.reload();
    });
  }
}

main();
